// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearTasks():Promise<void>;

export function CreateTask(arg1:main.Quadrant,arg2:number,arg3:number):Promise<main.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function ListTasks():Promise<Array<main.Task>>;

export function MoveTask(arg1:string,arg2:main.Quadrant,arg3:number,arg4:number):Promise<main.Task>;

export function UpdateTaskTitle(arg1:string,arg2:string):Promise<main.Task>;
