// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function MoveTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2, arg3, arg4);
}

export function UpdateTaskTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskTitle'](arg1, arg2);
}
